"""add tbl_blacklisted_tokens + refresh_token for user

Revision ID: 7575b5eedbd5
Revises: cd70e94074fb
Create Date: 2025-04-16 10:40:43.386196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575b5eedbd5'
down_revision = 'cd70e94074fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blacklisted_token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('tbl_users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'refresh_token')
    op.drop_table('tbl_blacklisted_tokens')
    # ### end Alembic commands ###
