"""init database

Revision ID: cd70e94074fb
Revises: 
Create Date: 2025-04-14 21:53:12.959804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd70e94074fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_banlist',
    sa.Column('ban_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('ban_id')
    )
    op.create_table('tbl_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.Column('chat_started', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_1_id'], ['tbl_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_2_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('tbl_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_id')
    )
    op.create_table('tbl_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('tbl_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('tbl_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tbl_chats.chat_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_messages')
    op.drop_table('tbl_profiles')
    op.drop_table('tbl_posts')
    op.drop_table('tbl_contacts')
    op.drop_table('tbl_chats')
    op.drop_table('tbl_banlist')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
