"""added reference to black token in user's model

Revision ID: bec4ce741585
Revises: 7575b5eedbd5
Create Date: 2025-04-16 10:56:16.620524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec4ce741585'
down_revision = '7575b5eedbd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
